baseURL = 'https://cael.li/hugo-demo/'
languageCode = 'en-us'
title = 'Hugo Site'
canonifyURLs = true 

[taxonomies]
# Use singular rather than plural for default taxonomies
tag = "tag"
category = "category"
type = "type"

[caches]
  [caches.images]
    dir = ':cacheDir/images'