baseURL = 'https://cael.li/'
# TODO: change base URL
languageCode = 'en-us'
title = 'Hugo Site'

[taxonomies]
# Use singular rather than plural for default taxonomies
tag = "tag"
category = "category"
type = "type"

[caches]
  [caches.images]
    dir = ':cacheDir/images'